config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

resources :users do
  resources :elections do
    resources :positions do
      resources :candidates do
        member do
          post 'upvote'
        end
      end
    end
  end
end

  #****** CLEARANCE routes that have been redefined for our project structure  ******
  # Probably don't need to touch these
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  #************************************************************

# base = "/user/:id/elections"
# #Election routes
# get "#{base}/new" => "elections#new", as: "new_election"
get "/user/:user_id/elections/:election_id/users" => "elections#show_users", as: "election_users"
get "/user/:user_id/elections/:election_id/users/add" => "elections#add_users", as: "add_users_to_election"
post "/user/:user_id/elections/:election_id/users/add" => "elections#add_users"
get "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users", as: "add_users_to_election_from_csv"
post "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users"
end

app/models/position.rb
class Position < ApplicationRecord
	belongs_to :election
	has_many :candidates, dependent: :destroy
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :require_login
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Election.find(params[:election_id]).positions
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)
    respond_to do |format|
      if @position.save
        format.html { redirect_to user_election_positions_path, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.fetch(:position, {}).permit(:election_id, :title, :description, :user_id)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<h1>Positions for <%= Election.find(params[:election_id]).title%></h1>
<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Candidates</th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |pos| %>
      <tr>
        <td><%=pos.title%></td>
        <td><%=pos.description%></td>
        <td><%= link_to 'Candidates', user_election_position_candidates_path(position_id: pos.id), :type => "button", :class=> 'btn btn-default' %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Position', new_user_election_position_path, :type => "button", :class=> 'btn btn-success' %>

app/views/positions/new.html.erb
<h1>New Position</h1>
<%= form_for(@position, url: user_election_positions_path(election_id: params[:election_id], user_id: params[:user_id]), method: :post) do |form| %>
  <div class="container">
    <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading"> <strong class="">Create a position:</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form">


                        <div class="form-group">
                            <label for="title" class="col-sm-3 control-label">Position Title:</label>
                            <div class="col-8">
                                <%= form.text_field :title, type: 'text', class: "form-control", placeholder: 'Title', required: ''%>
                            </div>
                        </div>

                        <label for="description" class="col-sm-3 control-label">Description:</label>
                            <div class="col-8">
                                <%= form.text_field :description, type: 'text', class: "form-control", placeholder: 'Description', required: ''%>
                            </div>
                        </div>

                        <%= form.hidden_field :election_id, :value => params[:election_id] %>

                        <div class="form-group last">
                            <div class="col-sm-offset-2 col-sm-9">
                                <button type="submit" class="btn btn-success btn-sm">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>
<% end %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>

<%= @position.id %>