config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

resources :users do
  resources :elections do
    resources :positions do
      resources :candidates do
        member do
          post 'upvote'
        end
      end
    end
  end
end

  #****** CLEARANCE routes that have been redefined for our project structure  ******
  # Probably don't need to touch these
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  #************************************************************

# base = "/user/:id/elections"
# #Election routes
# get "#{base}/new" => "elections#new", as: "new_election"
get "/user/:user_id/elections/:election_id/users" => "elections#show_users", as: "election_users"
get "/user/:user_id/elections/:election_id/users/add" => "elections#add_users", as: "add_users_to_election"
post "/user/:user_id/elections/:election_id/users/add" => "elections#add_users"
get "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users", as: "add_users_to_election_from_csv"
post "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users"
end

app/models/election.rb
class Election < ApplicationRecord
	validates :title, presence: true
	has_many :positions, dependent: :destroy
	has_and_belongs_to_many :users
end

app/controllers/elections_controller.rb
require 'csv'

class ElectionsController < ApplicationController
 before_action :require_login
 before_action :set_election, only: [:show, :edit, :update, :destroy]

 # GET /elections
 # GET /elections.json
 def index
   @elections = current_user.elections
 end

 def show
   @election = Election.find(params[:id])
 end

 # GET /elections/new
 def new
   @election = Election.new
 end

 # GET /elections/1/edit
 def edit
   @election = Election.find(params[:id])
 end

 # POST /elections
 # POST /elections.json
 def create
   @election = Election.new(election_params)
   respond_to do |format|
     if @election.save
       @election.users << current_user #add the current user to the users for this election
       #Mail the users of the election a notice that the election is closed and they should check the results
       UserMailer.send_results_email(@election.id).deliver_later(wait_until: @election.close_date)
       format.html { redirect_to user_elections_path, notice: 'Election was successfully created.' }
       format.json { render :show, status: :created, location: @election }
     else
       format.html { render :new }
       format.json { render json: @election.errors, status: :unprocessable_entity }
     end
   end
 end

 def show_users
   @users = Election.find(params[:election_id]).users
 end

 def csv_users
   #If the user uploaded a file
   if(!params[:users].nil? && !params[:users][:csv].nil?)
     election = Election.find(params[:election_id]) #The election we want to add the users to
     myFile = params[:users][:csv] #The csv file the user uploaded

     #Loop over each user in the file
     CSV.foreach(myFile.path) do |userEmail|
       #If the user is NOT already a user in this election
       if(election.users.where(email: userEmail)[0].nil?)
         #Then add them to the election
         election.users << User.where(email: userEmail)
       end
   end
   redirect_to election_users_path, notice: "Users were added"
 end
 end

 def add_users
     if(!params[:new_user].nil?)
     election = Election.find(params[:election_id])
     user = User.where(email: params[:new_user]).first
     if(!user.nil? && !election.users.where(email: user.email).nil?)
     election.users << user
     return redirect_to election_users_path, notice: "User was added"
   end
   return redirect_to election_users_path, notice: "User was not added"
     end
 end

 # PATCH/PUT /elections/1
 # PATCH/PUT /elections/1.json
 def update
   @election = Election.find(election_params[:id])
   respond_to do |format|
     if @election.update(election_params)
       format.html { redirect_to user_elections_path, notice: 'Election was successfully updated.' }
       format.json { render :show, status: :ok, location: @election }
     else
       format.html { render :edit }
       format.json { render json: @election.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /elections/1
 # DELETE /elections/1.json
 def destroy
   @election = Election.find(params[:id])
   @election.destroy
   respond_to do |format|
     format.html { redirect_to user_elections_path, notice: 'Election was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_election
     rescue ActiveRecord::RecordNotFound
      redirect_to :controller => "main", :action => "index"
      return
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def election_params
     params.fetch(:election, {}).permit(:title, :description, :election_id, :close_date, :id)
   end
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/add_users.html.erb
<h1>Add users</h1>
<%= form_for(:user1, url: add_users_to_election_path, method: :post) do |form| %>
  <div class="container">
    <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading"> <strong class="">Add a user</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label for="title" class="col-sm-2 control-label">User email</label>
                            <div class="col-sm-9">
                                <%= form.text_field :email, name: 'new_user', type: 'text', class: "form-control", placeholder: 'joe@pugetsound.edu', required: ''%>
                            </div>
                            <%= form.hidden_field :delete => true %>
                        </div>
                        <div class="form-group last">
                            <div class="col-sm-offset-2 col-sm-9">
                                <button type="submit" class="btn btn-success btn-sm">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>
<% end %>

app/views/elections/csv_users.html.erb
  <div class="jumbotron">
    <h1>Upload users from a csv</h1>
    <p>If you have an Excel file (from Log Jam;)) with the emails of all of the users you wish to add to your election this is the place for you!</p>
    <p>1) Make sure your file is formatted properly
    	<ul>
    		<li>Each users email ends with "@pugetsound.edu" (spelled all the way out, no @ups.edu!)</li>
    		<li>Each email is on a new row</li>
    		<li>All emails are in the same column</li>
    		<li>For example:</li>
    		<img src=<%= image_url('usersCSV.jpg')%> style="width:304px;height:228px;">
    		</ul>
    		</p>
    <p>2) Save the file as a .csv</p>
    <p>3) Upload the file below!</p>
    <p>NOTE: A user MUST already have an account to be added to an election.</p>
  </div>

<%= form_for(:users, url: add_users_to_election_from_csv_path, method: :post) do |form| %>
<label class="control-label">Select File</label>
  <%= form.file_field :csv, :class => "file" %>
       		<button type="submit" class="btn btn-success">Submit</button>

<% end %>

<td><%= link_to 'Users', election_users_path(election_id: params[:election_id]), :type=> "button", :class => "btn btn-default"%></td>

app/views/elections/edit.html.erb
<h1>Edit Election</h1>
<%= form_for(@election, url: user_election_path, method: :put) do |form| %>
 <div class="container">
   <div class="row">
           <div class="panel panel-default">
               <div class="panel-heading"> <strong class="">Edit election:</strong>
               </div>
               <div class="panel-body">
                   <form class="form-horizontal" role="form">

                   <%= form.hidden_field :id, :value =>  @election.id%>


                       <div class="form-group">
                           <label for="title" class="col-sm-3 control-label">Election Title:</label>
                           <div class="col-8">
                               <%= form.text_field :title, type: 'text', class: "form-control", placeholder: 'Title', required: ''%>
                           </div>
                       </div>

                      <div class="form-group-fluid">
                      <label for="description" class="col-sm-3 control-label">Description:</label>
                           <div class="col-8">
                               <%= form.text_field :description, type: 'text', class: "form-control", placeholder: 'Description', required: ''%>
                           </div>
                       </div>

                       <div class="form-group last">
                           <div class="col-sm-offset-2 col-sm-9">
                               <button type="submit" class="btn btn-success btn-sm">Submit</button>
                           </div>
                       </div>
                   </form>
               </div>
       </div>
   </div>
</div>
<% end %>

app/views/elections/index.html.erb
<h1>Elections</h1>
<p id="notice"><%= notice %></p>
<table class="table table-inverse">
  <thead>
    <tr class="active">
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Positions</th>
      <th>Users</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @elections.each do |election| %>
      <tr class="active">
        <td><u><%=election.title%></u></td>
        <td><%=election.description%></td>
        <% if election.close_date > Time.now  %>
        <td> <strong>Open,</strong> ending at: <%=election.close_date%> </td>
        <% else %>
        <td> <strong>Closed,</strong> finished at: <%=election.close_date%> </td>
        <% end %>
        <td><%= link_to 'Positions', user_election_positions_path(election_id: election.id), :type => "button", :class=> 'btn btn-default' %></button></td>
        <td><%= link_to 'Users', election_users_path(election_id: election.id), :type => "button", :class=> 'btn btn-default' %></button></td>
        <td><%= link_to 'Update', edit_user_election_path(id: election.id), :type => "button", :class=> 'btn btn-default' %></button></td>
        <td><%= link_to 'Delete', user_election_path(id: election.id), data: { confirm: 'Are you sure?' }, :method => :delete, :type => "button", :class=> 'btn btn-default'%></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/elections/new.html.erb
<h1>New Election</h1>
<%= form_for(@election, url: user_elections_path, method: :post) do |form| %>
  <div class="container">
    <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading"> <strong class="">Create an election</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form">

                        <div class="form-group">
                            <label for="title" class="col-sm-2 control-label">Date:</label>
                            <div class="col-sm-9">
                                <%= form.datetime_select :close_date, :ampm => true %>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="title" class="col-sm-3 control-label">Election Title:</label>
                            <div class="col-8">
                                <%= form.text_field :title, type: 'text', class: "form-control", placeholder: 'Title', required: ''%>
                            </div>
                        </div>

                       <div class="form-group">
                       <label for="description" class="col-sm-3 control-label">Description:</label>
                            <div class="col-8">
                                <%= form.text_field :description, type: 'text', class: "form-control", placeholder: 'Description', required: ''%>
                            </div>
                        </div>

                        <div class="form-group last">
                            <div class="col-sm-offset-2 col-sm-9">
                                <button type="submit" class="btn btn-success btn-sm">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>
</div>
<% end %>

app/views/elections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <h1><%= @election.title %></br></h1>
  <div class="col-md-4">
  <%= @election.description %></br>
  <%= @election.start_date %>
  <%= @election.close_date %>
  </div>
  
</p>

<<td><%= link_to 'Positions', user_election_positions_path(election_id: @election.id) %></td>

app/views/elections/show_users.html.erb
<h1>Users allowed to vote in <%= Election.find(params[:election_id]).title%></h1>
<p id="notice"><%= notice %></p>
<table class="table table-bordered">
  <thead>
    <tr class="active">
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="active">
        <td><%= user.email%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add users', add_users_to_election_path(user_id: params[:user_id], election_id: params[:election_id]), :type => "button", :class=> 'btn btn-success' %>
<div></div>
<br>
<%= link_to 'Add from CSV', add_users_to_election_from_csv_path(user_id: params[:user_id], election_id: params[:election_id]), :type => "button", :class=> 'btn btn-warning' %>