config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

resources :users do
  resources :elections do
    resources :positions do
      resources :candidates do
        member do
          post 'upvote'
        end
      end
    end
  end
end

  #****** CLEARANCE routes that have been redefined for our project structure  ******
  # Probably don't need to touch these
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  #************************************************************

# base = "/user/:id/elections"
# #Election routes
# get "#{base}/new" => "elections#new", as: "new_election"
get "/user/:user_id/elections/:election_id/users" => "elections#show_users", as: "election_users"
get "/user/:user_id/elections/:election_id/users/add" => "elections#add_users", as: "add_users_to_election"
post "/user/:user_id/elections/:election_id/users/add" => "elections#add_users"
get "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users", as: "add_users_to_election_from_csv"
post "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users"
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :position
  has_many :votes, dependent: :destroy
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :require_login
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    # @candidates = Candidate.all
    @candidates = Position.find(params[:position_id]).candidates
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)
    respond_to do |format|
      if @candidate.save
        format.html { redirect_to user_election_position_candidates_path, notice: 'Candidate was successfully created.' }
        format.json { render :show, status: :created, location: @candidate }
      else
        format.html { render :new }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
    respond_to do |format|
      if @candidate.update(candidate_params)
        format.html { redirect_to user_election_position_candidates_path, notice: 'Candidate was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidate }
      else
        format.html { render :edit }
        format.json { render json: @candidate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    respond_to do |format|
      format.html { redirect_to candidates_url, notice: 'Candidate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    #Get all of this users prvious votes
    previousVotes = Vote.where(user_id: params[:user_id])
    previousVotes.each do |prevVote|
      #If this user has already voted for someone in this position
      if(prevVote[:position_id] == params[:position_id].to_i && prevVote[:user_id] == params[:user_id].to_i)
        return redirect_to(user_election_position_candidates_path, :notice => 'You have already voted for a candidate in this position.')
      end
    end
    #The user hasn't already voted for someone in this position so save their vote
      @candidate = Candidate.find(params[:id])
      vote = @candidate.votes.new(candidate_id: params[:id], user_id: params[:user_id], position_id: params[:position_id], election_id: params[:election_id])
      vote.save
      redirect_to(user_election_position_candidates_path, :notice => "Your vote has been recorded.")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.fetch(:candidate, {}).permit(:name, :biography, :position_id, :id)

    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<table class="table">
    <p id="notice"><%=notice %></p>
    <h1>Candidates for <%= Position.find(params[:position_id]).title%></h1>
    <thead>
        <tr>
            <th>Name</th>
            <th>Biography</th>
        </tr>
    </thead>
    <tbody>
        <% @candidates.each do |candidate| %>
            <tr>
                <td>
                    <%=candidate.name%>
                </td>
                <td>
                    <%=candidate.biography%>
                </td>
                <td>
                    <%=pluralize(candidate.votes.count, "vote") %>
                </td>
                <% if Election.find(params[:election_id]).close_date > Time.now %>
                    <td>
                        <%=button_to '+1',upvote_user_election_position_candidate_path(id: candidate.id), method: :post %>
                    </td>
                    <%else%>
                        <td>Election is closed</td>
                        <%end %>
            </tr>
            <% end %>
    </tbody>
</table>
<br>
<%=link_to 'New Candidate', new_user_election_position_candidate_path, :type => "button", :class=> 'btn btn-success' %>
    <div>
        <%=link_to 'Back', user_election_positions_path, :type => "button", :class=> 'btn btn-default' %>
    </div>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>
<%= form_for(@candidate, url: user_election_position_candidates_path(election_id: params[:election_id], user_id: params[:user_id]), method: :post) do |form| %>
  <div class="container">
    <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading"> <strong class="">Create a candidate</strong>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label for="name" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-9">
                                <%= form.text_field :name, type: 'text', class: "form-control", placeholder: 'Name', required: ''%>
                            </div>
                        </div>
                        <label for="biography" class="col-sm-2 control-label">Biography</label>
                            <div class="col-sm-9">
                                <%= form.text_area :biography, type: 'text', class: "form-control", placeholder: 'About me ...'%>
                            </div>
                            <div class="form-group last">
                                <div class="col-sm-offset-2 col-sm-9">
                                    <button type="submit" class="btn btn-success btn-sm">Submit</button>
                                </div>
                            </div>
                        </div>
                        <%= form.hidden_field :position_id, :value => params[:position_id] %>
                    </form>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @candidate.biography %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>