config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

resources :users do
  resources :elections do
    resources :positions do
      resources :candidates do
        member do
          post 'upvote'
        end
      end
    end
  end
end

  #****** CLEARANCE routes that have been redefined for our project structure  ******
  # Probably don't need to touch these
  resources :passwords, controller: "passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "passwords",
      only: [:create, :edit, :update]
  end
  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  #************************************************************

# base = "/user/:id/elections"
# #Election routes
# get "#{base}/new" => "elections#new", as: "new_election"
get "/user/:user_id/elections/:election_id/users" => "elections#show_users", as: "election_users"
get "/user/:user_id/elections/:election_id/users/add" => "elections#add_users", as: "add_users_to_election"
post "/user/:user_id/elections/:election_id/users/add" => "elections#add_users"
get "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users", as: "add_users_to_election_from_csv"
post "/user/:user_id/elections/:election_id/users/csv" => "elections#csv_users"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Opine</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header", style="font-weight:bold">
      <%= link_to image_tag("Opine_Logo.jpg", :size => "50x50", :class => "navbar-header-text"), root_path, class: 'navbar-header-text' %>
    </div>
    <ul class="nav navbar-nav">
        <% if !current_user.nil?%>
        <li><%= link_to 'New Election',  new_user_election_path(current_user)%></li>
        <li><%= link_to 'All Elections', user_elections_path(current_user)%></li>
        <% else %>
        <li><%= link_to 'New Election',  sign_in_path%></li>
        <li><%= link_to 'All Elections', sign_in_path%></li>
        <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if signed_in? %>
      <li><%= link_to 'Account', current_user%><li>
      <li><%= link_to 'Sign out', sign_out_path, method: :delete%></li>
    <% else %>
    <li><a href=<%= sign_up_path%>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href=<%= sign_in_path%>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <% end %>
    </ul>
  </div>
</nav>
    <%= yield %>

  </body>
</html>